package:
  name: openvisus
  version: 1.3.56

source:
  path: ../..

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - git
    - swig
    - cmake

  host:
    - python
  run:
    - python
    - numpy

test:
  imports:
    - OpenVisus

about:
  home: http://github.com/sci-visus/OpenVisus
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Open Source Implementation of VISUS'
  description: The mission of ViSUS.org is to provide support for the scientific community with Big Data, management, analysis and visualization tools
