title: "OpenViSUS Documentation"
remote_theme: just-the-docs/just-the-docs

aux_links:
  "OpenViSUS on GitHub":
    - "https://github.com/sci-visus/OpenVisus"

gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/sci-visus/OpenVisus"
gh_edit_branch: "gh-pages"
gh_edit_view_mode: "tree"