#!/bin/bash

# verbose
# set -x

#  -e  Exit immediately if a command exits with a non-zero status.
set -e

# fix datasets permissions problems 
# http-foreground switch from root to daemon, so daemon needs to be in the same group of the mounted datasets directory
if [ -d "/datasets" ] ; then
	
	chmod a+rx /datasets
	GID=$(stat -c "%g" /datasets)
	
	# they can fail in case the group already exists
	addgroup --gid $GID mygroup || true
	
	# daomon (the user that httpd uses for workers) should be added to the group
	usermod -a -G $GID daemon   || true

	# fix permissions on password file
	if [ -f /datasets/.htpasswd ];  then
		chmod 644 /datasets/.htpasswd
	fi
  
fi

# FROM HERE original httpd-foreground from httpd Docker Image
rm -f /usr/local/apache2/logs/httpd.pid

exec httpd -DFOREGROUND "$@"