FROM opensuse:leap

ARG PYTHON_VERSION=3.6.6
ARG GIT_BRANCH=master   
ARG VISUS_GUI=1

ADD https://api.github.com/repos/sci-visus/OpenVisus/git/refs/heads/$GIT_BRANCH version.json
RUN zypper --non-interactive install git
RUN git clone -b${GIT_BRANCH} https://github.com/sci-visus/OpenVisus.git /home/OpenVisus  

WORKDIR /home/OpenVisus 
RUN chmod +x ./build.sh 
RUN ./build.sh




  















