# see https://github.com/tashrifbillah/glxgears-containers
# sudo apt-get install -y mesa-utils libgl1-mesa-glx
# sudo docker build --tag test-opengl -f Dockerfile .
# xhost +
# sudo docker run --rm -ti -v /tmp/.X11-unix:/tmp/.X11-unix -e DISPLAY=$DISPLAY --privileged test-opengl glxgears

FROM centos:7.5.1804

WORKDIR /tmp/

RUN yum -y install xauth xeyes glx-utils wget
RUN yum -y install glx-utils mesa-dri-drivers.x86_64
 